server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:54322/category_module
    username: postgres
    password: postgres2206
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


