server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb+srv://crrinconm:GVVIuwK25MwRVyUh@clone-reddit.rzy9bqv.mongodb.net/?retryWrites=true&w=majority
      database: fileposts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  registerWithEureka: true
  fetchRegistry: true