server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comment_module
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  registerWithEureka: true
  fetchRegistry: true